[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "../.targets/x86_64-quay-kernel.json"

[target.x86_64-quay-kernel]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=-z", "-C", "link-arg=max-page-size=0x1000",
    "-C", "link-arg=-z", "-C", "link-arg=norelro"
]
