timeout: 10

/Quay
    protocol: limine
    comment: A small micro-kernel and OS written in Rust
    kernel_path: boot():/quay/v0.0.1/quay-kernel
    resolution: 1920x1080x32
    paging_mode: 4level
