MODE := "debug"
PROFILE := if MODE == "debug" { "dev" } else { "release" }

# Default recipe
run: build

# Just compile the kernel
build:
    cargo build --target ../.targets/x86_64-quay-kernel.json --profile {{PROFILE}}